### ISSUE TITLE
提示： Coding Pages 自定义域名服务会有广告跳转页

### ISSUE THREAD

**Issue by Bazinga-Wang** [ruby-china/gethomeland.com#10]
您好，我是 Coding 的工作人员，在无意中我发现，https://gethomeland.com/ 页面会出现 Coding 的广告跳转页面，这是由于您将网页搭载在 coding pages 服务上，并且选择了自定义域名的方式访问。
您可以在页面任意位置放置 Hosted by Coding Pages 字样，并且在部署时勾选去广告审核以取出广告。

感谢您使用我们的服务。

Best Wishes.

**Comment by huacnlee** [comment]
增加文字就不会有提示了么

**Comment by Bazinga-Wang** [comment]
是的。
广告页将不再出现。


不过由于是人工审核，您需要在 pages 部署页面勾选“以放置 Hosted by Coding Pages”，后台一个工作日内会进行审核。


原始邮件
发件人:Jason Leenotifications@github.com
收件人:ruby-china/gethomeland.comgethomeland.com@noreply.github.com
抄送:wangizying45372020@qq.com; Authorauthor@noreply.github.com
发送时间:2017年8月7日(周一) 15:34
主题:Re: [ruby-china/gethomeland.com] 提示： Coding Pages 自定义域名服务会有广告跳转页 (#10)


增加文字就不会有提示了么

**Comment by huacnlee** [comment]
我是用 Git Push 的方式自动部署的，Web 界面上没有找到勾选项

**Comment by Bazinga-Wang** [comment]
您好，麻烦您看一下您的会员等级，完善资料成为银牌会员即可有相关选项。
是我没说清楚。


原始邮件
发件人:Jason Leenotifications@github.com
收件人:ruby-china/gethomeland.comgethomeland.com@noreply.github.com
抄送:wangizying45372020@qq.com; Authorauthor@noreply.github.com
发送时间:2017年8月7日(周一) 15:42
主题:Re: [ruby-china/gethomeland.com] 提示： Coding Pages 自定义域名服务会有广告跳转页 (#10)


我是用 Git Push 的方式自动部署的，Web 界面上没有找到勾选项

**Comment by huacnlee** [comment]
已经填好了

**Comment by Bazinga-Wang** [comment]
收到，已经审核通过了。
之后访问不会有跳转页面了。


感谢您的使用。


原始邮件
发件人:Jason Leenotifications@github.com
收件人:ruby-china/gethomeland.comgethomeland.com@noreply.github.com
抄送:wangizying45372020@qq.com; Authorauthor@noreply.github.com
发送时间:2017年8月7日(周一) 15:53
主题:Re: [ruby-china/gethomeland.com] 提示： Coding Pages 自定义域名服务会有广告跳转页 (#10)


已经填好了
