### ISSUE TITLE
wanjiaoyi.com采用homeland搭建

### ISSUE THREAD

**Issue by lutaf** [ruby-china/gethomeland.com#2]
<https://wanjiaoyi.com>
裸机安装 ,安装说明 <https://wanjiaoyi.com/topics/9> 希望能帮到其它用户

**Comment by huacnlee** [comment]
欢迎转发安装记录到 Ruby China

**Comment by huacnlee** [comment]
已加入列表

**Comment by lutaf** [comment]
@huacnlee  请帮忙转一下啊，我在ruby-china还不能发主贴

**Comment by huacnlee** [comment]
@lutaf 告诉我账号，我给你开通权限
