### ISSUE TITLE
install 文档，获取 homeland-docker 的项目，cd 后才能 git checkout

### ISSUE THREAD

**Issue by sanlengjingvv** [ruby-china/gethomeland.com#4]
http://gethomeland.com/install/

测试结果： 
<img width="594" alt="2017-01-11 2 19 13" src="https://cloud.githubusercontent.com/assets/6478615/21837792/68c6cd16-d809-11e6-86a9-1a6b4a0f4b82.png">

期望结果：  
```
git clone https://github.com/ruby-china/homeland-docker.git
cd homeland-docker/
git checkout v2.4.2 # 切换到 stable 版本
```

在 master 分支，source/install.html.md 里怎么找不到这句？`git checkout v2.4.2 # 切换到 stable 版本`

**Comment by huacnlee** [comment]
不需要  checkout v2.4.2 了
